name: Run Ansible playbook
description: Execute Ansible playbook on selected hosts
branding:
  color: red
  icon: play
inputs:
  playbook:
    description: Ansible playbook filepath
    required: true
  directory:
    description: Root directory of Ansible project (defaults to current)
    required: false
  key:
    description: SSH private key used to connect to the host
    required: true
  options:
    description: Extra options that should be passed to ansible-playbook command
    required: false
runs:
  using: docker
  image: Dockerfile
