name: Test Action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      host:
        image: dawidd6/alpine-for-ansible
        env:
          SSH_PUBLIC_KEY: ${{secrets.SSH_PUBLIC_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./
        with:
          playbook: playbook.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory=user@host,
            --verbose